Repository GeunH/Online-BoardGame, pull requests merged in 2024-04, with the labels that each got.

#2 [FE] 개발 환경 설정
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: chore, FE

#6 [BE] 개발 초기 세팅
  .project
  .settings/org.eclipse.buildship.core.prefs
  .settings/org.springframework.ide.eclipse.xml.namespaces.prefs
  BE/WebGame/.gitignore
  BE/WebGame/build.gradle
  BE/WebGame/gradle/wrapper/gradle-wrapper.jar
  BE/WebGame/gradle/wrapper/gradle-wrapper.properties
  BE/WebGame/gradlew
  BE/WebGame/gradlew.bat
  BE/WebGame/settings.gradle
  BE/WebGame/src/main/java/webgame/GameAppliaction.java
  BE/WebGame/src/main/java/webgame/config/SwaggerConfig.java
  BE/WebGame/src/main/resources/application.properties
  BE/WebGame/src/test/java/com/example/demo/WebGameApplicationTests.java
Labels: chore, BE

#7 [FE] 회원가입 페이지 구성
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/components/Common/Button.tsx
  frontend/src/components/Common/Header.tsx
  frontend/src/pages/Register.tsx
  frontend/src/util/constants.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: feat, FE
